// Mocks generated by Mockito 5.4.6 from annotations
// in joey_mcp_client_flutter/test/sampling_request_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i5;
import 'package:joey_mcp_client_flutter/services/openrouter_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OpenRouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenRouterService extends _i1.Mock implements _i2.OpenRouterService {
  MockOpenRouterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getApiKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String startAuthFlow() =>
      (super.noSuchMethod(
            Invocation.method(#startAuthFlow, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#startAuthFlow, []),
            ),
          )
          as String);

  @override
  _i3.Future<String> exchangeCodeForKey(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForKey, [code]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#exchangeCodeForKey, [code]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> chatCompletion({
    required String? model,
    required List<Map<String, dynamic>>? messages,
    List<Map<String, dynamic>>? tools,
    dynamic toolChoice,
    bool? stream = false,
    int? maxTokens,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#chatCompletion, [], {
              #model: model,
              #messages: messages,
              #tools: tools,
              #toolChoice: toolChoice,
              #stream: stream,
              #maxTokens: maxTokens,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<String> chatCompletionStream({
    required String? model,
    required List<Map<String, dynamic>>? messages,
    List<Map<String, dynamic>>? tools,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#chatCompletionStream, [], {
              #model: model,
              #messages: messages,
              #tools: tools,
              #cancelToken: cancelToken,
            }),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getModels() =>
      (super.noSuchMethod(
            Invocation.method(#getModels, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}
